use warehouse chipmunk_wh;
use database chipmunk_db;
create schema if not exists chipmunk_lab11;
use schema chipmunk_lab11;

CREATE OR REPLACE TABLE STG_GA_NATIONAL_ROADS AS 
SELECT * FROM TRANSPORT__LINES_AND_FIXTURES__AUSTRALIA__FREE.TRANSPORT_AUS_FREE.GA_NATIONAL_ROADS_AUS_GDA2020;

CREATE OR REPLACE TABLE STG_GA_MAJOR_ROADS AS 
SELECT * FROM TRANSPORT__LINES_AND_FIXTURES__AUSTRALIA__FREE.TRANSPORT_AUS_FREE.GA_MAJOR_ROADS_AUS_GDA2020;


CREATE OR REPLACE TABLE STG_GA_PETROL_STATIONS AS 
SELECT * FROM TRANSPORT__LINES_AND_FIXTURES__AUSTRALIA__FREE.TRANSPORT_AUS_FREE.GA_PETROL_STATION_LOCATIONS_GDA2020;


CREATE OR REPLACE TABLE STG_OSM_EV_CHARGERS AS 
SELECT * FROM TRANSPORT__LINES_AND_FIXTURES__AUSTRALIA__FREE.TRANSPORT_AUS_FREE.OSM_ELECTRIC_VEHICLE_CHARGERS_LOCATION_GDA2020;


CREATE OR REPLACE TABLE STG_GA_RAILWAY_LINES AS 
SELECT * FROM TRANSPORT__LINES_AND_FIXTURES__AUSTRALIA__FREE.TRANSPORT_AUS_FREE.GA_RAILWAY_LINES_AUS_GDA2020;

CREATE OR REPLACE TABLE STG_GA_RAILWAY_STATIONS AS 
SELECT * FROM TRANSPORT__LINES_AND_FIXTURES__AUSTRALIA__FREE.TRANSPORT_AUS_FREE.GA_RAILWAY_STATIONS_AUS_GDA2020;



CREATE OR REPLACE TABLE DIM_STATE AS
SELECT ROW_NUMBER() OVER (ORDER BY state_code) AS idDIM_STATE,state_code,
CASE 
WHEN state_code = 'NSW' THEN 'New South Wales'
WHEN state_code = 'VIC' THEN 'Victoria'
WHEN state_code = 'QLD' THEN 'Queensland'
WHEN state_code = 'WA' THEN 'Western Australia'
WHEN state_code = 'SA' THEN 'South Australia'
WHEN state_code = 'TAS' THEN 'Tasmania'
WHEN state_code = 'ACT' THEN 'Australian Capital Territory'
WHEN state_code = 'NT' THEN 'Northern Territory'
ELSE 'Unknown'
END AS state_name
FROM (SELECT DISTINCT STATION_STATE AS state_code FROM STG_GA_PETROL_STATIONS);

CREATE OR REPLACE TABLE DIM_LOCATION AS
SELECT 
ROW_NUMBER() OVER (ORDER BY state_code, suburb_name) AS idDIM_LOCATION,state_code,suburb_name,postal_code
FROM (
SELECT DISTINCT 
STATION_STATE AS state_code, 
STATION_SUBURB AS suburb_name, 
STATION_POSTCODE::VARCHAR AS postal_code 
FROM STG_GA_PETROL_STATIONS
);


CREATE OR REPLACE TABLE DIM_ROAD_INFO AS
SELECT 
ROW_NUMBER() OVER (ORDER BY hierarchy) AS idDIM_ROAD_INFO,
HIERARCHY AS hierarchy,
STREET_NAME AS street_name,
SURFACE AS surface_type,
TRAFFICABILITY AS trafficability
FROM (SELECT DISTINCT HIERARCHY, STREET_NAME, SURFACE, TRAFFICABILITY FROM STG_GA_NATIONAL_ROADS);




CREATE OR REPLACE TABLE DIM_STATION_INFO AS
SELECT 
ROW_NUMBER() OVER (ORDER BY NAME) AS idDIM_STATION_INFO,
NAME AS station_name,
OPERATOR AS operator,
FUEL_TYPE AS fuel_type
FROM (
SELECT DISTINCT STATION_NAME AS NAME, STATION_OWNER AS OPERATOR, 'Petrol' AS FUEL_TYPE FROM STG_GA_PETROL_STATIONS
UNION ALL
SELECT DISTINCT NAME, OPERATOR, 'Electric' AS FUEL_TYPE FROM STG_OSM_EV_CHARGERS
);

CREATE OR REPLACE TABLE DIM_INFRASTRUCTURE_TYPE AS
SELECT 
ROW_NUMBER() OVER (ORDER BY infra_type) AS idDIM_INFRASTRUCTURE_TYPE,infra_type,category
FROM (
SELECT 'Road' AS infra_type, 'Transport' AS category
UNION SELECT 'Railway', 'Transport'
UNION SELECT 'Fuel Station', 'Service'
);



CREATE OR REPLACE TABLE DIM_TIME AS
SELECT 
ROW_NUMBER() OVER (ORDER BY date) AS idDIM_TIME,
date, day, month, year, quarter
FROM (
SELECT DISTINCT 
DATE_CREATED::DATE AS date,
DAY(DATE_CREATED) AS day,
MONTHNAME(DATE_CREATED) AS month,
YEAR(DATE_CREATED) AS year,
QUARTER(DATE_CREATED) AS quarter
FROM STG_GA_NATIONAL_ROADS WHERE DATE_CREATED IS NOT NULL
);





CREATE OR REPLACE TABLE FACT_TRANSPORT_INFRASTRUCTURE AS
SELECT 
UUID_STRING() AS idFACT_TRANSPORT_INFRASTRUCTURE,
src.LANE_COUNT AS lane_count,
src.SPEED AS speed,
src.SHAPE_LENGTH AS shape_length,
RANK() OVER (PARTITION BY src.STATE ORDER BY src.SHAPE_LENGTH DESC) AS road_rank_in_state,
AVG(src.SPEED) OVER (PARTITION BY src.HIERARCHY) AS avg_speed_category,
s.idDIM_STATE,
l.idDIM_LOCATION,
ri.idDIM_ROAD_INFO,
si.idDIM_STATION_INFO,
it.idDIM_INFRASTRUCTURE_TYPE,
t.idDIM_TIME
FROM STG_GA_NATIONAL_ROADS src
LEFT JOIN DIM_STATE s ON src.STATE = s.state_code
LEFT JOIN DIM_LOCATION l ON src.STATE = l.state_code AND src.STREET_NAME = l.suburb_name
LEFT JOIN DIM_ROAD_INFO ri ON src.HIERARCHY = ri.hierarchy AND src.STREET_NAME = ri.street_name
LEFT JOIN DIM_TIME t ON src.DATE_CREATED::DATE = t.date
CROSS JOIN (SELECT idDIM_INFRASTRUCTURE_TYPE FROM DIM_INFRASTRUCTURE_TYPE WHERE infra_type = 'Road' LIMIT 1) it
LEFT JOIN (SELECT idDIM_STATION_INFO FROM DIM_STATION_INFO LIMIT 1) si ON 1=1;




SELECT 
lane_count, 
speed, 
avg_speed_category, 
road_rank_in_state 
FROM FACT_TRANSPORT_INFRASTRUCTURE 
LIMIT 10;



DROP TABLE IF EXISTS STG_GA_NATIONAL_ROADS;
DROP TABLE IF EXISTS STG_GA_MAJOR_ROADS;
DROP TABLE IF EXISTS STG_GA_PETROL_STATIONS;
DROP TABLE IF EXISTS STG_OSM_EV_CHARGERS;
DROP TABLE IF EXISTS STG_GA_RAILWAY_LINES;
DROP TABLE IF EXISTS STG_GA_RAILWAY_STATIONS;

